"""Specifications for defining commands and parameters."""

from ._arity import (
    Arity,
    get_arity_min,
    is_fixed_range_arity,
    is_greedy_arity,
    is_optional_arity,
    is_optional_scalar_arity,
    is_scalar_arity,
    is_unbounded_arity,
    is_variadic_arity,
    is_zero_arity,
    validate_arity,
)
from ._command import CommandSpecification, PositionalSpecification
from ._factories import (
    command,
    dict_list_option,
    dict_option,
    flag_option,
    flat_list_option,
    list_option,
    nested_list_option,
    scalar_option,
)
from ._options import (
    DictAccumulationMode,
    DictMergeStrategy,
    DictOptionSpecification,
    FlagAccumulationMode,
    FlagOptionSpecification,
    ListAccumulationMode,
    ListOptionSpecification,
    OptionSpecification,
    OptionType,
    ScalarAccumulationMode,
    ScalarOptionSpecification,
    is_counting_flag_option,
    is_dict_list_option,
    is_dict_option,
    is_flag_option,
    is_list_option,
    is_multi_value_option,
    is_nested_list_option,
    is_optional_scalar_option,
    is_scalar_option,
)
from .helpers import flatten_string_iterables

__all__ = [
    "Arity",
    "CommandSpecification",
    "DictAccumulationMode",
    "DictMergeStrategy",
    "DictOptionSpecification",
    "FlagAccumulationMode",
    "FlagOptionSpecification",
    "ListAccumulationMode",
    "ListOptionSpecification",
    "OptionSpecification",
    "OptionType",
    "PositionalSpecification",
    "ScalarAccumulationMode",
    "ScalarOptionSpecification",
    "command",
    "dict_list_option",
    "dict_option",
    "flag_option",
    "flat_list_option",
    "flatten_string_iterables",
    "get_arity_min",
    "is_counting_flag_option",
    "is_dict_list_option",
    "is_dict_option",
    "is_fixed_range_arity",
    "is_flag_option",
    "is_greedy_arity",
    "is_list_option",
    "is_multi_value_option",
    "is_nested_list_option",
    "is_optional_arity",
    "is_optional_scalar_arity",
    "is_optional_scalar_option",
    "is_scalar_arity",
    "is_scalar_option",
    "is_unbounded_arity",
    "is_variadic_arity",
    "is_zero_arity",
    "list_option",
    "nested_list_option",
    "scalar_option",
    "validate_arity",
]
